FROM jenkins/jenkins:lts

USER root

# Встановлюємо Python і pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir pytest

# Додаємо venv до PATH, щоб Jenkins міг викликати pytest і pip
ENV PATH="/opt/venv/bin:$PATH"

USER jenkins